[profile.default]
contracts = "contracts"
tests = "tests"
scripts = "scripts"
out = "out"
libs = ["lib", "node_modules"]

optimizer = true
optimizer-runs = 200
solc_version = "0.8.20"
evm_version = "istanbul"
